name: Push File

on:
  push:
    branches:
      - main

env:
  sha: $GITHUB_SHA

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Mark test file
      run: |-
        echo $GITHUB_SHA > test02.md
        echo $GITHUB_SHA > test03.md
        echo $GITHUB_SHA > test04.md

    - name: Ignore unchanged file
      uses: ./
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_pattern: 'test01.md'
        destination_repo: 'c0mplexity0/release-test'
        user_email: '106925362+C0mplexity0@users.noreply.github.com'
        user_name: 'C0mplexity0'

    - name: Push changed file
      uses: ./
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_pattern: 'test02.md'
        destination_repo: 'c0mplexity0/release-test'
        user_email: '106925362+C0mplexity0@users.noreply.github.com'
        user_name: 'C0mplexity0'

    - name: Check custom commit message
      uses: ./
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_pattern: 'test03.md'
        destination_repo: 'c0mplexity0/release-test'
        user_email: '106925362+C0mplexity0@users.noreply.github.com'
        user_name: 'C0mplexity0'
        commit_message: 'A custom message.'

    - name: Check rsync runs
      uses: ./
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_pattern: 'test04.md'
        destination_repo: 'c0mplexity0/release-test'
        user_email: '106925362+C0mplexity0@users.noreply.github.com'
        user_name: 'C0mplexity0'
        use_rsync: 'true'

    - name: Push renamed file
      uses: ./
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_pattern: 'test02.md'
        destination_repo: 'c0mplexity0/release-test'
        user_email: '106925362+C0mplexity0@users.noreply.github.com'
        user_name: 'C0mplexity0'
        rename: 'test02_rename.md'

    - name: Push pattern
      uses: ./
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_pattern: 'testfiles/foo.!(rst)'
        destination_repo: 'c0mplexity0/release-test'
        user_email: '106925362+C0mplexity0@users.noreply.github.com'
        user_name: 'C0mplexity0'
        rename: 'test02_rename.md'
