name: Push File

on:
  push:
    branches:
      - main

env:
  sha: $GITHUB_SHA

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push pattern
      uses: ./
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_pattern: 'testfiles/foo.!(rst)'
        destination_repo: 'c0mplexity0/release-test'
        user_email: '106925362+C0mplexity0@users.noreply.github.com'
        user_name: 'C0mplexity0'
